name: collegebustracking
description: "SAEC Spotbus"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  provider: ^6.1.1
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  intl: ^0.19.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.3
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0

  # google_map alternative flutter_map_location for driver.
  wakelock: ^0.6.2
  rename_app: ^1.3.2
  shared_preferences: ^2.0.0
  firebase_remote_config: ^4.0.0
  firebase_analytics: ^10.3.1
  background_location: ^0.13.0
  audiofileplayer: ^2.1.1




dev_dependencies:

  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/saec_staff.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/img/
    - assets/audio/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
