// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshkySFRBRVWJgtJyyI5LBd3kMrPRwugI',
    appId: '1:415882333790:android:0d5ce9c65ac5f0fb8c6ecf',
    messagingSenderId: '415882333790',
    projectId: 'saec-bus-database',
    databaseURL: 'https://saec-bus-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saec-bus-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMghKRjcfo5-Yzyhjm2NjluC7EHUNW5BA',
    appId: '1:415882333790:ios:5f2247ff5b5ce37d8c6ecf',
    messagingSenderId: '415882333790',
    projectId: 'saec-bus-database',
    databaseURL: 'https://saec-bus-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saec-bus-database.appspot.com',
    iosBundleId: 'com.example.collegebustracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMghKRjcfo5-Yzyhjm2NjluC7EHUNW5BA',
    appId: '1:415882333790:ios:f4747ef6f194311a8c6ecf',
    messagingSenderId: '415882333790',
    projectId: 'saec-bus-database',
    databaseURL: 'https://saec-bus-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saec-bus-database.appspot.com',
    iosBundleId: 'com.example.collegebustracking.RunnerTests',
  );
}
